spring:
  application:
    name: appointment-microservice

  datasource:
    url: jdbc:h2:mem:appointment
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true

  graphql:
    graphiql:
      enabled: true
      path: /graphiql

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:user}
    password: ${RABBITMQ_PASSWORD:123456}
    virtual-host: /
    connection-timeout: 60000

app:
  rabbitmq:
    exchange: appointment.exchange
    routing-key: appointment.notification
    queue: appointment.notification.queue

logging:
  level:
    com.fiap.postech.techchallenge: INFO
    org.springframework.amqp: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

server:
  port: 8080